config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  resources :orders
  resources :line_items
  resources :carts

  get 'store/index'
	resources :products do
    get :who_bought, on: :member
  end

  root 'store#index', as: 'store'

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Tasty Bagels
    %link{:href => "http://fonts.googleapis.com/css?family=Erica+One", :rel => "stylesheet", :type => "text/css"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true 
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

    %body{:class => controller.controller_name} 
      #banner
        / = image_tag("logo.png")
        %h1#heading 
          Welcome To Tasty Bagel
          %span#subheading Try our simple ordering service!

        #process
          %i.grow.fa.fa-hand-o-down
            %span.fasubhead Pick bagel.
          %i.fa.fa-chevron-right
          %i.grow.fa.fa-paper-plane
            %span.fasubhead Ship bagel.
          %i.fa.fa-chevron-right
          %i.grow.fa.fa-cutlery
            %span.fasubhead Eat Bagel.

      #columns
        #side
          #cart
            - if @cart
              = hidden_div_if(@cart.line_items.empty?, id: 'cart') do
                = render @cart
          %ul
            %li
              %a{:href => '/'} Home
            %li
              %a{:href => '/login'} Login
            

          - if session[:user_id]
            %ul
              %li
                = link_to "Orders", orders_path
              %li
                = link_to "Products", products_path
              %li
                = link_to "Users", users_path
            = button_to "Logout", logout_path, method: :delete

        #main
          = yield